name: SleepNotify
version: 0.3
main: zerrium.SleepNotify
api-version: 1.12
author: zerrium
softdepend: [Essentials]
commands:
   t:
      description: Tell what time it is in your current dimension
      usage: /t
      permission: SleepNotify.whattime