name: SleepNotify
version: 0.1
main: zerrium.SleepNotify
api-version: 1.13
author: zerrium
commands:
   t:
      description: Tell what time it is in your current dimension
      usage: /t
      permission: SleepNotify.whattime